### ISSUE TITLE
Short term TODO

### ISSUE THREAD

**Issue by ottojo** [ToolboxPlane/PowerDeliveryBoard#37]
- [x] Decide Power Connector for Pi (suggestion: XT30 -> weird cable to micro USB)
- [x] Add VBAT pins for peripherals
- [x] Verify (fix) XT(3|6)0 footprints
- [x] Power LEDs
- [x] LTC2946 Supply by something else than VIN
- [x] Label LEDs
- [ ] Eval LMZ21700SILR

**Comment by aul12** [comment]
- [x] 8 LEDs instead of 4
- [x] Reset Button
